services:
    nginx:
        image: nginx:latest
        ports:
            - "9090:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx:/etc/nginx/conf.d

    php:
        build:
            context: .
        volumes:
            - ./:/var/www/html

