services:
    app:
        build:
            context: .
            dockerfile: ./.docker/dev-apache/Dockerfile
        volumes:
            - ./:/var/www/html
        ports:
            - "9090:80"
        networks:
            - custom_network

    redis:
        container_name: redis
        image: 'redis:alpine'
        command: redis-server --requirepass someredispassword
        networks:
            - custom_network

    queue-redis:
        restart: always
        build:
            context: .
            dockerfile: ./.docker/dev-apache/Dockerfile
        volumes:
            - ./:/var/www/html
        networks:
            - custom_network
        command: php artisan queue:work
        depends_on:
            - redis

    typesense:
        image: typesense/typesense:27.1
        restart: on-failure
        ports:
            - "8108:8108"
        volumes:
            - typesense-data:/data
        command: '--data-dir /data --api-key=masterKey --enable-cors'
        networks:
            - custom_network

volumes:
    typesense-data:


networks:
    custom_network:
        external: true
