services:
  nginx:
    image: nginx:latest
    ports:
      - "9090:80"
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx:/etc/nginx/conf.d
    networks:
      - custom_network

  php:
    build:
      context: .
    volumes:
      - ./:/var/www/html
      - ./.docker/php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./.docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    networks:
      - custom_network

  redis:
    container_name: redis
    image: 'redis:alpine'
    command: redis-server --requirepass someredispassword
    networks:
      - custom_network

  queue-redis:
    restart: always
    build:
      context: .
    volumes:
      - ./:/var/www/html
    networks:
      - custom_network
    command: php artisan queue:work
    depends_on:
      - redis

  typesense:
    image: typesense/typesense:27.1
    restart: on-failure
    ports:
      - "8108:8108"
    volumes:
      - typesense-data:/data
    # command: '--data-dir /data --api-key=masterKey --enable-cors'
    command: '--data-dir /data --api-key=masterKey'
    networks:
      - custom_network

volumes:
  typesense-data:


networks:
  custom_network:
    external: true
